#!/usr/bin/env python3
"""Generate reviewed WebOps methodology/tool skills and routing fixtures."""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
SKILLS=ROOT/"skills"

# name, trigger, sources, steps, outputs, limits
ROWS=[
("webops-site-profile","configuring or validating a portable WebOps site profile, repository binding, integration references, permission default, or site identity","WebOps profile schema and Agency Runner site profiles",["Resolve the profile and schema without following symlinks outside its root.","Validate site ID, HTTP(S) URL, optional repository, platform, capabilities, integrations, and default permission.","Reference credential environment variables; never embed values.","Emit a normalized profile or exact validation errors."],["validated profile","capability declarations","credential references","permission default"],"A site profile grants no capability or ACT authority by itself."),
("webops-capability-preflight","checking which WebOps website, repository, browser, search, analytics, performance, backlink, keyword, publishing, distribution, or submission capabilities are available","WebOps capability schema plus tool doctor/capabilities outputs",["Load the site profile and requested agent contract.","Check required, recommended, and optional capabilities independently.","Record provider, evidence mode, missing environment reference, cost/write boundary, and degradation path.","Stop only when a required capability has no honest degraded mode."],["capability receipt","available/unavailable matrix","degraded execution decision"],"Never repeatedly prompt for credentials or convert unavailable evidence into zero."),
("webops-longitudinal-findings","creating, comparing, or updating stable WebOps findings, recommendations, actions, outcomes, and recurring-run history","WebOps finding/history schemas and prior run artifacts",["Read the previous relevant run, unresolved findings, and actions.","Normalize agent/check, target, and issue identity into a deterministic ID.","Classify NEW, PERSISTENT, RESOLVED, REGRESSED, or REOPENED from evidence.","Store finding, recommendation, action, and outcome as separate records."],["finding records","state transitions","comparison summary","history update"],"A recommendation is not an action; an action does not prove causation."),
("kujo-siteprobe-workflows","running, validating, comparing, reporting, or integrating SiteProbe website-intelligence crawls and `.siteprobe` artifacts","`../siteprobe` README, CLI, schemas, tests, and security contract",["Run `siteprobe doctor` and select a bounded same-origin target.","Use `siteprobe crawl <url> --max-pages N --max-depth N --max-output-bytes N --max-report-tokens N --out <run>`; preserve robots compliance by default.","Run `siteprobe validate <run>` before consuming artifacts.","Use `compare`, `report`, `links`, or `sitemap` for the narrow downstream need."],["validated SiteProbe run","pages/links/findings artifacts","comparison evidence"],"SiteProbe is not Lens, Scout, a JS renderer, SEO advisor, security scanner, form submitter, or cross-origin crawler."),
("kujo-searchbridge-workflows","running SearchBridge doctor, capability preflight, fixture providers, normalized evidence reads, or explicit ACT submission","`../searchbridge` README, provider research, schemas, tests, and security contract",["Run `searchbridge doctor`, `capabilities`, and `providers` without credentials.","Use `--fixture` for deterministic GSC, GA4, PageSpeed, CrUX, Bing, Ahrefs, and IndexNow coverage.","For live reads, supply short-lived environment credentials and bounded dimensions/rows.","For submission require the operator's `index.submission` capability and ACT authority plus `submit --capability index.submission --act --yes`; retain the receipt."],["normalized result/v1 evidence","capability matrix","ACT submission receipt"],"SearchBridge fetches evidence and never invents interpretation; a received submission is not proof of indexing."),
("kujo-contentgraph-workflows","building, inspecting, comparing, exporting, or consuming deterministic ContentGraph artifacts","`../contentgraph` README, methodology, schemas, tests, and security contract",["Select validated SiteProbe, local source, and optional SearchBridge inputs.","Run `contentgraph build` with explicit node/output/report budgets and reviewed thresholds.","Inspect clusters, orphans, overlaps, related pages, and link opportunities as candidates.","Use `compare` for longitudinal graph changes and `export` for downstream systems."],["contentgraph graph/v1","nodes/edges","clusters/overlaps/orphans","link opportunities"],"Lexical similarity is not semantic truth, cannibalization proof, or permission to mutate content."),
("webops-technical-seo","performing a deterministic technical SEO audit from crawl evidence","SiteProbe artifacts, WebOps history, and optional Lens/inspection evidence",["Validate crawl coverage and robots/sitemap state.","Evaluate statuses, redirects, canonicals, indexability, metadata, structured data, and internal graph conditions.","Separate crawl-visible facts from rendered or provider-confirmed state.","Prioritize reproducible findings and delegate specialized interpretation."],["technical findings","affected URLs","severity/evidence","specialist handoffs"],"Do not emulate a search engine, perform vulnerability scans, or claim local indexability means indexed."),
("webops-search-performance","analyzing longitudinal measured search performance","SearchBridge search.performance result/v1 and prior comparable windows",["Validate provider, property, date range, dimensions, and freshness.","Compare impressions, clicks, CTR, position, query/page movement, and incomplete-data metadata.","Control for incompatible dimensions and periods.","Label correlation and uncertainty; connect content evidence only when identifiers match."],["period comparison","query/page movement","measured anomalies","unavailable dimensions"],"Never invent measurements or treat average position as a fixed rank."),
("webops-indexation","auditing crawlability, local indexability, and confirmed provider index state","SiteProbe robots/sitemap/page artifacts and optional SearchBridge URL inspection",["Classify crawl access, response, canonical, robots, noindex, and sitemap membership.","Label local conclusions `appears indexable` or `appears not indexable`.","Add `confirmed indexed/not indexed` only from current provider evidence.","Track conflicts and follow-up verification separately from submission."],["local indexability matrix","confirmed index evidence","conflicts","coverage gaps"],"Do not infer indexed from HTTP 200, sitemap presence, or canonical alone."),
("webops-keyword-opportunity","finding query opportunities while separating measurement, estimates, and public research","SearchBridge search/keyword results, public research, and ContentGraph coverage",["Classify each input as measured, third-party estimate, or public observation.","Associate queries with existing pages and topic clusters.","Score opportunity from evidence quality, relevance, coverage gap, and business fit rather than volume alone.","Report missing provider families explicitly."],["opportunity candidates","evidence class","coverage relationship","confidence"],"Do not present keyword estimates as measured site demand or guarantee rankings."),
("webops-ai-search-visibility","running repeatable AI/search visibility benchmark suites","Fixed query suite, configured surfaces, dated response evidence, and prior benchmark",["Freeze query text, locale, surface/model, configuration, and collection window.","Run only available surfaces and preserve exact availability.","Record observed mentions/citations with source evidence.","Compare like-for-like runs and flag surface/model changes."],["benchmark run","surface availability","observed citations/mentions","longitudinal comparison"],"Do not fabricate citations, universalize one surface, or claim stable GEO certainty."),
("webops-content-gap","classifying site coverage against audience/search needs","ContentGraph corpus, research, optional query data, and current site profile",["Build a normalized set of audience/search needs with provenance.","Map each need to content nodes and evidence.","Classify covered well, partially covered, stale, weak, missing, or irrelevant.","Distinguish genuine audience value from competitor mimicry."],["coverage matrix","gap classifications","supporting nodes","evidence gaps"],"A competitor page or keyword estimate alone does not establish a valuable content gap."),
("webops-content-decay","identifying content deterioration or staleness without conflating age and decline","SearchBridge longitudinal results, ContentGraph, factual sources, analytics, and history",["Validate comparable search/analytics windows and content identity.","Evaluate measured movement separately from factual age, source change, and structural signals.","Classify measurement, inference, and unknowns.","Recommend refresh only when evidence names what should change and why."],["decay candidates","measured/inferred evidence","confidence","refresh rationale"],"Without provider data, do not claim measured decline; old content is not automatically stale."),
("webops-internal-linking","analyzing, proposing, or explicitly applying contextual internal links","ContentGraph opportunities, page context, SiteProbe links, optional repository",["Validate source/target relevance and user journey in context.","Reject redundant, forced, or count-driven opportunities.","Propose natural anchor intent and exact source location.","Apply only under role-bounded ACT, then run Eval, SiteProbe, and Lens as applicable."],["reviewed link proposals","source/target context","optional patch","post-change proof"],"Do not force exact-match anchors or mutate content under OBSERVE/PROPOSE."),
("webops-content-accuracy","reviewing website claims for outdated or invalid guidance","Current authoritative primary sources, content corpus, and retrieval provenance",["Extract material verifiable claims and their existing references.","Research current primary sources and record retrieval dates.","Classify valid, outdated, unsupported, ambiguous, or unverifiable.","Produce minimal source-grounded corrections and escalation for editorial judgment."],["claim review","authoritative sources","correction brief","unverified claims"],"Do not treat snippets as sources, fabricate authority, or silently change editorial intent."),
("webops-cannibalization","identifying likely intent competition while separating normal overlap","ContentGraph overlaps plus SearchBridge query/page evidence",["Start with high lexical overlap candidates, not conclusions.","Compare intent, SERP/query associations, page purpose, canonical state, and longitudinal performance.","Classify normal overlap, supporting cluster, or likely cannibalization.","Recommend differentiation, merge, canonical, or no action with evidence."],["intent comparison","candidate classification","query/page evidence","bounded recommendation"],"Shared terms alone do not prove cannibalization."),
("webops-content-portfolio","assigning longitudinal content portfolio states","ContentGraph, search, analytics, backlink, freshness, and business-purpose evidence",["Validate content identity and prior state.","Evaluate usefulness, accuracy, differentiation, relationships, demand, performance, and maintenance cost.","Assign CREATE, GROW, MAINTAIN, REFRESH, MERGE, REDIRECT, RETIRE, or IGNORE with rationale.","Record confidence, approval boundary, and next measurement."],["portfolio state","rationale","confidence","review horizon"],"Portfolio state is a proposal, not an executed redirect or retirement."),
("webops-content-pruning","reviewing obsolete or redundant content for keep, refresh, merge, redirect, or retire proposals","ContentGraph, accuracy review, measured providers, backlinks, and business context",["Identify redundancy, invalidity, obsolete purpose, maintenance burden, and unique value.","Check search, analytics, backlinks, links, conversions, and non-traffic utility when available.","Model destination and redirect implications before recommending removal.","Require approval and migration proof for ACT."],["pruning candidates","retain/refresh/merge/redirect/retire rationale","risk and destination plan"],"Never recommend deletion solely because traffic is low."),
("webops-information-architecture","auditing site navigation, hierarchy, taxonomy, URLs, depth, clusters, and discoverability","ContentGraph, SiteProbe graph/depth, Lens navigation evidence, and source structure",["Map navigation, hierarchy, categories, tags, breadcrumbs, URL patterns, and content clusters.","Identify orphaning, excessive depth, weak connections, duplicate taxonomy, and user-journey gaps.","Separate crawl graph from rendered navigation.","Propose incremental architecture changes with URL migration implications."],["IA map","discoverability findings","taxonomy/URL risks","sequenced proposals"],"Do not redesign taxonomy from graph metrics alone or change URLs without redirect planning."),
("webops-schema-and-metadata","auditing structured data and page/social metadata","SiteProbe metadata/structured-data artifacts, visible content, and current authoritative guidance",["Validate titles, descriptions, canonicals, robots, Open Graph, social/article metadata, and JSON-LD syntax.","Check structured data relevance and consistency with visible content.","Identify duplicates, omissions, obsolete patterns, and conflicts.","Propose only source-supported values/types and verify after changes."],["metadata matrix","schema findings","duplicates/conflicts","repair brief"],"Do not invent visible facts, keyword-stuff, or guarantee rich results."),
("webops-web-performance","analyzing lab and field website performance as distinct evidence classes","SearchBridge PageSpeed/CrUX, Lens environment-relative metrics, and prior runs",["Label each metric lab, field, or local environment-relative.","Validate device/form factor, URL/origin, collection period, and comparable configuration.","Compare distributions/percentiles separately from lab audits.","Connect regressions to changes only when evidence supports the relationship."],["lab results","field results","comparison","bounded hypotheses"],"Do not merge lab and field values or infer causation from timing alone."),
("webops-accessibility-review","running repeatable automated accessibility review with explicit manual gaps","Lens accessibility artifacts, rendered routes, and applicable manual review",["Define representative routes, states, and viewports.","Run deterministic automated checks and inspect evidence.","Group repeated root causes without hiding affected instances.","Name required manual keyboard, screen-reader, cognition, motion, and content checks."],["automated findings","affected routes/components","repair priorities","manual-review gaps"],"Automation cannot certify full WCAG conformance."),
("webops-link-health","auditing broken, redirected, malformed, or unexpected links","SiteProbe link/status/redirect evidence and optional Lens interactions",["Validate crawl coverage and response timestamps.","Separate internal breakage, outbound observation, redirect chains, malformed URLs, and unexpected destinations.","Recheck transient external failures conservatively.","Propose exact source/target repairs and verify under authorized ACT."],["link inventory findings","redirect chains","transient/confirmed labels","repair brief"],"Do not crawl cross-origin sites broadly or equate one timeout with permanent failure."),
("webops-competitor-intelligence","monitoring selected public competitors or peers for meaningful change","Public web evidence, bounded SiteProbe runs, optional SearchBridge estimates, and prior baseline",["Use an explicit peer list and lawful public scope.","Compare topics, positioning, structure, notable content, search presence, and available backlinks.","Separate observed change, third-party estimate, and analyst inference.","Explain relevance without recommending imitation by default."],["peer change log","evidence URLs","relevance assessment","unknowns"],"Do not infer private strategy or bypass crawl restrictions."),
("webops-backlink-and-mention-analysis","analyzing new/lost backlinks, linked and unlinked mentions, and evidence-backed link concerns","SearchBridge backlink data, public web research, and prior run",["Validate provider coverage, target, retrieval window, and cost boundary.","Compare stable link identities for new/lost state.","Research relevant mentions and distinguish linked/unlinked.","Label suspicious patterns cautiously and preserve provider/public-web limitations."],["new/lost links","mention inventory","unlinked candidates","evidence-backed risks"],"Without a provider, do not claim complete backlink change coverage or create disavow actions."),
("webops-search-standards-watch","monitoring authoritative search, indexing, structured-data, analytics, browser, AI-search, and web-standard changes","Official search-engine, analytics, browser, standards-body, and provider documentation",["Use primary authoritative sources and record publication/retrieval dates.","Distinguish final guidance, deprecation, experiment, draft standard, and rumor.","Assess applicability against the site profile and current implementation.","Create a bounded watch finding only when action or monitoring is warranted."],["standards change record","authority/status","site applicability","recommended follow-up"],"Do not amplify SEO rumor or treat draft guidance as settled."),
("webops-search-submission","preflighting or performing explicit ACT search submission through supported providers","SearchBridge providers/capabilities, site ownership, approved URL list, and receipt schema",["Verify provider support, ownership, URL host, quota/cost, and ACT authorization.","Preview the exact URL set and reject cross-host or unsupported Google Indexing API use.","Run SearchBridge submission with explicit confirmation.","Store receipt as received/accepted only and schedule independent index verification."],["preflight","approved URL set","submission receipt","future verification cue"],"Never submit in OBSERVE/PROPOSE, bypass quotas, or claim guaranteed indexing."),
("webops-analytics-analysis","analyzing real website behavior from normalized analytics evidence","SearchBridge analytics result/v1, property identity settings, dimensions, metrics, and prior window",["Validate property, identity/reporting settings, date range, dimensions, metrics, sampling/modeling metadata, and freshness.","Compare like-for-like periods and segment only when necessary.","Describe measured behavior separately from explanations.","Minimize sensitive dimensions in artifacts and handoffs."],["measured behavior summary","segment evidence","comparison","privacy/coverage caveats"],"Without an analytics provider, stop measured analysis; crawl data is not analytics."),
("webops-distribution","creating source-grounded distribution assets and optionally publishing with ACT authority","Approved published content, Howl, distribution integration, permission receipt, and brand constraints",["Confirm source content is approved and published.","Derive claims, links, metadata, and channel variants without inventing content.","Generate and validate local Howl assets first.","Publish only to configured destinations under explicit ACT and retain receipts."],["distribution asset pack","source map","validation","optional publication receipts"],"Without integration or ACT, stop at local reviewable assets."),
("webops-reporting","synthesizing validated specialist evidence into quiet WebOps reports","Validated current/prior WebOps artifacts, finding history, actions, outcomes, and availability receipts",["Validate input runs and specialist ownership.","Lead with what improved, regressed, changed, requires action, can wait, and could not be checked.","Deduplicate persistent findings by stable ID and keep full evidence machine-readable.","Do not redo specialist analysis or convert recommendations into claimed actions."],["quiet human report","machine evidence references","attention queue","availability summary"],"A large pass count must not bury a few actionable findings."),
]

def render(row):
    name,trigger,sources,steps,outputs,limits=row
    title=" ".join(x.capitalize() if x not in {"seo","ai"} else x.upper() for x in name.split("-"))
    numbered="\n".join(f"{i}. {step}" for i,step in enumerate(steps,1))
    output_lines="\n".join(f"- {x}." for x in outputs)
    return f'''---
name: {name}
description: "Use when {trigger}."
---

# {title}

## Purpose

Use this skill for {trigger}. Its primary sources are {sources}.

## Workflow

{numbered}

## Required Output

{output_lines}

Every output must name target/scope, evidence class, retrieval or run time,
unavailable checks, permission mode, and comparison baseline where applicable.

## Boundaries

{limits} Preserve OBSERVE/PROPOSE/ACT boundaries, provider cost and credential
limits, stable finding identity, and the distinction among finding,
recommendation, action, and outcome. Never store credentials or fabricate
provider data, rankings, indexing, citations, compliance, or causation.

## Verification

Validate source artifacts with their owning tool before interpretation. Run
the current repository's WebOps cross-reference validation when agent, skill,
tool, capability, or workflow mappings change.
'''

def main():
    for row in ROWS:
        folder=SKILLS/row[0]; folder.mkdir(exist_ok=True); (folder/"SKILL.md").write_text(render(row),encoding="utf-8")
    index=ROOT/"SKILLS_INDEX.md"; text=index.read_text(); marker="\n## WebOps skills\n"
    if marker in text: text=text.split(marker)[0].rstrip()+"\n"
    rows="\n".join(f'| `{name}` | {trigger[0].upper()+trigger[1:]}. | {sources} |' for name,trigger,sources,*_ in ROWS)
    index.write_text(text+marker+"\n| Skill | Use when | Primary sources |\n|---|---|---|\n"+rows+"\n",encoding="utf-8")
    expected=ROOT/"evals/expected-skill-map.md"; text=expected.read_text(); marker="\n## WebOps routing\n"
    if marker in text: text=text.split(marker)[0].rstrip()+"\n"
    rows="\n".join(f'| {trigger[0].upper()+trigger[1:]} | `{name}` |' for name,trigger,*_ in ROWS)
    expected.write_text(text+marker+"\n| Query theme | Expected skill(s) |\n|---|---|\n"+rows+"\n",encoding="utf-8")
    triggers_path=ROOT/"evals/trigger-queries.json"; triggers=json.loads(triggers_path.read_text())
    for name,trigger,*_ in ROWS:
        triggers[name]={"should_trigger":[f"Use {name} for {trigger}",f"I need help {trigger}"],"should_not_trigger":["write a generic Python hello world","summarize an unrelated PDF"]}
    triggers_path.write_text(json.dumps(triggers,indent=2)+"\n",encoding="utf-8")
    print(f"Generated {len(ROWS)} WebOps skills")

if __name__=="__main__": main()
